name: Capture Webpage Screenshots

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  capture-screenshots:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Using a more recent Node.js version

    - name: Install dependencies
      run: |
        npm init -y
        npm install puppeteer@13.0.0  # Specifying an older version for compatibility

    - name: Set IST Time
      id: ist-time
      run: |
        ist_time=$(TZ=Asia/Kolkata date +'%Y-%m-%d_%H-%M-%S')
        echo "ist_time=$ist_time" >> $GITHUB_OUTPUT

    - name: Capture Screenshots
      run: |
        node << EOF
        const puppeteer = require('puppeteer');

        async function captureScreenshot(url, filename) {
          let browser;
          try {
            browser = await puppeteer.launch({
              args: ['--no-sandbox', '--disable-setuid-sandbox']
            });
            const page = await browser.newPage();
            await page.setViewport({ width: 1920, height: 1080 });
            await page.goto(url, { waitUntil: 'networkidle0', timeout: 60000 });
            await page.screenshot({ path: filename, fullPage: true });
            console.log(`Screenshot captured: ${filename}`);
          } catch (error) {
            console.error(`Error capturing screenshot for ${url}:`, error);
          } finally {
            if (browser) await browser.close();
          }
        }

        (async () => {
          const timestamp = process.env.IST_TIME;
          await captureScreenshot('https://chartink.com/screener/daily-combine', `daily_combine_${timestamp}.png`);
          await captureScreenshot('https://chartink.com/screener/weekly-must-before-all-check', `weekly_must_before_all_check_${timestamp}.png`);
        })();
        EOF
      env:
        IST_TIME: ${{ steps.ist-time.outputs.ist_time }}

    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.png
        git commit -m "Captured screenshots at ${{ steps.ist-time.outputs.ist_time }} IST" || echo "No changes to commit"
        git push || echo "No changes to push"

    - name: Output Action Status
      run: |
        echo "Action completed"
        echo "Current UTC time: $(date -u)"
        echo "Files created:"
        ls -l *.png || echo "No PNG files found"
