name: Capture Webpages

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]  # Triggers on push to main branch

permissions:
  contents: write  # Explicitly set permissions to write to the repository

jobs:
  capture-webpages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set IST Time
      id: ist-time
      run: |
        ist_time=$(TZ=Asia/Kolkata date +'%Y-%m-%d_%H-%M-%S')
        echo "ist_time=$ist_time" >> $GITHUB_OUTPUT

    - name: Capture Daily Combine Webpage
      run: |
        wget -O "daily_combine_${{ steps.ist-time.outputs.ist_time }}.html" https://chartink.com/screener/daily-combine

    - name: Capture Weekly Must Before All Check Webpage
      run: |
        wget -O "weekly_must_before_all_check_${{ steps.ist-time.outputs.ist_time }}.html" https://chartink.com/screener/weekly-must-before-all-check

    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Captured webpages at ${{ steps.ist-time.outputs.ist_time }} IST"
        git push

    - name: Output Action Status
      run: |
        echo "Action completed successfully"
        echo "Current UTC time: $(date -u)"
        echo "Files created:"
        ls -l *.html
